HelenaTest:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: polestartrial # Replace this with your project id
      dataset: airbyte_prod_configapi # Replace this with dbt_your_name, e.g. dbt_bob
      threads: 4
      timeout_seconds: 300
      location: EU
      priority: interactive
      keyfile: "{{ env_var('BIGQUERY_KEYFILE') }}"
