HelenaTest:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: polestartrial
      dataset: airbyte_prod_configapi
      threads: 1
      keyfile: C:\Users\Helena Geginat\Documents\bigquery_creds.json
      timeout_seconds: 300
