soccer_538:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: soccer538-369314
      dataset: 538_football
      threads: 1
      keyfile: "{{ env_var('BIGQUERY_KEYFILE') }}"
      timeout_seconds: 300
