version: 1

models:
  - name: Sheet1
    description: Table with the information of Download of apps from the applestore
  - name: mart_polestar_info
    description: Table with the information of Downloads only in Stockholm
